services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:2.2.17@sha256:802ab7d045826d047883476e2310bf59f5d9b3875f7a8106fa0c43638d01fd64
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    env_file:
      - /custom/files/miniflux.env
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.miniflux.rule=Host(`miniflux.${SECRET_INTERNAL_DOMAIN_NAME}`)
      - traefik.http.routers.miniflux.tls=true
      - traefik.http.routers.miniflux.tls.certresolver=cloudflare
      - traefik.http.routers.miniflux.entrypoints=websecure
      - traefik.http.services.miniflux.loadbalancer.server.port=8080

networks:
  proxy:
    external: true
